INFO - 2023-09-03 05:08:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:08:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:09:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:09:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:11:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:11:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:12:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:12:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:12:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:12:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:13:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:15:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:15:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:15:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:16:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:16:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:17:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:17:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:18:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:18:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:18:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:19:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:19:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:20:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:20:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:26:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:26:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:26:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:28:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 05:28:42 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: invalid sslmode value: &quot;1&quot; in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:72
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\ci4\\GoodYear...', 72)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(72): pg_connect('host=hostname p...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\ci4\GoodYear\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\ci4\GoodYear\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\GoodYear\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#8 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#9 C:\ci4\GoodYear\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#10 C:\ci4\GoodYear\system\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#11 C:\ci4\GoodYear\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#12 C:\ci4\GoodYear\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\GoodYear\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\GoodYear\system\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear...')
#15 {main}
CRITICAL - 2023-09-03 05:28:42 --> Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: invalid sslmode value: &quot;1&quot;
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "roles"
WHERE "username" = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 05:47:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 05:47:36 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: invalid sslmode value: &quot;1&quot; in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:72
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\ci4\\GoodYear...', 72)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(72): pg_connect('host=hostname p...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\ci4\GoodYear\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\ci4\GoodYear\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\GoodYear\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#8 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#9 C:\ci4\GoodYear\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#10 C:\ci4\GoodYear\system\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#11 C:\ci4\GoodYear\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#12 C:\ci4\GoodYear\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\GoodYear\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\GoodYear\system\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear...')
#15 {main}
CRITICAL - 2023-09-03 05:47:36 --> Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: invalid sslmode value: &quot;1&quot;
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "roles"
WHERE "username" = :username:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 6 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
 7 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
 8 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
 9 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 05:47:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:47:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 05:49:03 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: invalid sslmode value: "1" in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:72
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\ci4\\GoodYear...', 72)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(72): pg_connect('host=hostname p...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\ci4\GoodYear\system\Database\BaseConnection.php(1409): CodeIgniter\Database\BaseConnection->query('SELECT "table_n...')
#5 C:\ci4\GoodYear\system\Database\BaseConnection.php(1428): CodeIgniter\Database\BaseConnection->listTables()
#6 C:\ci4\GoodYear\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#7 C:\ci4\GoodYear\system\Database\MigrationRunner.php(168): CodeIgniter\Database\MigrationRunner->ensureTable()
#8 C:\ci4\GoodYear\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\ci4\GoodYear\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\ci4\GoodYear\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\ci4\GoodYear\spark(97): CodeIgniter\CLI\Console->run()
#12 {main}
INFO - 2023-09-03 05:57:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:57:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:58:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:58:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:58:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:58:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2023-09-03 05:58:44 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 762.
 1 SYSTEMPATH\BaseModel.php(762): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([], false)
 3 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 4 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 5 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptRegister()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 05:59:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:59:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 05:59:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:03:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:03:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:03:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:04:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:04:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2023-09-03 06:04:32 --> There is no data to insert.
in SYSTEMPATH\BaseModel.php on line 762.
 1 SYSTEMPATH\BaseModel.php(762): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
 2 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([], false)
 3 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
 4 VENDORPATH\myth\auth\src\Controllers\AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
 5 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptRegister()
 6 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 06:07:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:07:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:07:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 06:07:23 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^ in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\ci4\\GoodYear...', 187)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\ci4\GoodYear\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\ci4\GoodYear\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\GoodYear\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#8 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#9 C:\ci4\GoodYear\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#10 C:\ci4\GoodYear\system\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#11 C:\ci4\GoodYear\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#12 C:\ci4\GoodYear\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\GoodYear\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\GoodYear\system\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear...')
#15 {main}
CRITICAL - 2023-09-03 06:07:23 --> pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = \'mfajrihusaini05@gmail.com\'
              ^', 'C:\\ci4\\GoodYear\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 5 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "roles"
WHERE "email" = :email:
 LIMIT 1', [...], false)
 6 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 8 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 9 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
10 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
11 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
12 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
13 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 06:20:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 06:20:49 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^ in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\ci4\\GoodYear...', 187)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\ci4\GoodYear\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\ci4\GoodYear\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\GoodYear\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#8 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#9 C:\ci4\GoodYear\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#10 C:\ci4\GoodYear\system\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#11 C:\ci4\GoodYear\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#12 C:\ci4\GoodYear\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\GoodYear\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\GoodYear\system\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear...')
#15 {main}
CRITICAL - 2023-09-03 06:20:49 --> pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = \'mfajrihusaini05@gmail.com\'
              ^', 'C:\\ci4\\GoodYear\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 5 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "roles"
WHERE "email" = :email:
 LIMIT 1', [...], false)
 6 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 8 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 9 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
10 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
11 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
12 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
13 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 06:20:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:20:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:23:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:50:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:50:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:50:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:52:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:53:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:55:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:55:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:56:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:57:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:57:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:58:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 06:58:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:01:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:01:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:03:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:05:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:05:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:06:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:06:07 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:06:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:09:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:09:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:11:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:11:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:11:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:12:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:12:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:12:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:51:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:52:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:52:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:52:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:55:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:55:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:55:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:55:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:55:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:55:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:55:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:55:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:55:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:55:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:56:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:56:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:58:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:59:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:59:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 07:59:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:01:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:01:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:02:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:03:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:03:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:03:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:06:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:06:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:07:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:07:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:07:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:07:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:07:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:07:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:07:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:08:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:08:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:08:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:08:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:09:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:10:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:11:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:11:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:11:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:11:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:11:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:12:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:13:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:13:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:13:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:13:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:13:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:13:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:13:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:13:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:13:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:14:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:14:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:14:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:15:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:15:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:15:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:15:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:15:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:15:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:15:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:15:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:15:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:18:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:18:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 08:18:38 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^ in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\ci4\\GoodYear...', 187)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\ci4\GoodYear\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\ci4\GoodYear\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\GoodYear\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#8 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#9 C:\ci4\GoodYear\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#10 C:\ci4\GoodYear\system\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#11 C:\ci4\GoodYear\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#12 C:\ci4\GoodYear\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\GoodYear\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\GoodYear\system\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear...')
#15 {main}
CRITICAL - 2023-09-03 08:18:38 --> pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = \'mfajrihusaini05@gmail.com\'
              ^', 'C:\\ci4\\GoodYear\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 5 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "roles"
WHERE "email" = :email:
 LIMIT 1', [...], false)
 6 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 8 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 9 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
10 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
11 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
12 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
13 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 08:22:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 08:22:02 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^ in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\ci4\\GoodYear...', 187)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\ci4\GoodYear\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\ci4\GoodYear\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\GoodYear\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#8 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#9 C:\ci4\GoodYear\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#10 C:\ci4\GoodYear\system\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#11 C:\ci4\GoodYear\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#12 C:\ci4\GoodYear\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\GoodYear\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\GoodYear\system\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear...')
#15 {main}
CRITICAL - 2023-09-03 08:22:02 --> pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = \'mfajrihusaini05@gmail.com\'
              ^', 'C:\\ci4\\GoodYear\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 5 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "roles"
WHERE "email" = :email:
 LIMIT 1', [...], false)
 6 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 8 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 9 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
10 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
11 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
12 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
13 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 08:25:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:25:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 08:25:10 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^ in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\ci4\\GoodYear...', 187)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\ci4\GoodYear\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\ci4\GoodYear\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\GoodYear\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#8 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#9 C:\ci4\GoodYear\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#10 C:\ci4\GoodYear\system\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#11 C:\ci4\GoodYear\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#12 C:\ci4\GoodYear\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\GoodYear\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\GoodYear\system\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear...')
#15 {main}
CRITICAL - 2023-09-03 08:25:10 --> pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = \'mfajrihusaini05@gmail.com\'
              ^', 'C:\\ci4\\GoodYear\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 5 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "roles"
WHERE "email" = :email:
 LIMIT 1', [...], false)
 6 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 8 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 9 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
10 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
11 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
12 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
13 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 08:29:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 08:29:54 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^ in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\ci4\\GoodYear...', 187)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\ci4\GoodYear\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\ci4\GoodYear\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\GoodYear\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#8 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#9 C:\ci4\GoodYear\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#10 C:\ci4\GoodYear\system\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#11 C:\ci4\GoodYear\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#12 C:\ci4\GoodYear\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\GoodYear\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\GoodYear\system\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear...')
#15 {main}
CRITICAL - 2023-09-03 08:29:54 --> pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = \'mfajrihusaini05@gmail.com\'
              ^', 'C:\\ci4\\GoodYear\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 5 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "roles"
WHERE "email" = :email:
 LIMIT 1', [...], false)
 6 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 8 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 9 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
10 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
11 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
12 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
13 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 08:29:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 08:29:58 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^ in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\ci4\\GoodYear...', 187)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\ci4\GoodYear\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\ci4\GoodYear\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\GoodYear\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#8 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#9 C:\ci4\GoodYear\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#10 C:\ci4\GoodYear\system\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#11 C:\ci4\GoodYear\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#12 C:\ci4\GoodYear\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\GoodYear\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\GoodYear\system\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear...')
#15 {main}
CRITICAL - 2023-09-03 08:29:58 --> pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = \'mfajrihusaini05@gmail.com\'
              ^', 'C:\\ci4\\GoodYear\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 5 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "roles"
WHERE "email" = :email:
 LIMIT 1', [...], false)
 6 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 8 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 9 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
10 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
11 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
12 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
13 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 08:30:49 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:30:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:30:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:31:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 08:31:08 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^ in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\ci4\\GoodYear...', 187)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\ci4\GoodYear\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\ci4\GoodYear\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\GoodYear\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#8 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#9 C:\ci4\GoodYear\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#10 C:\ci4\GoodYear\system\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#11 C:\ci4\GoodYear\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#12 C:\ci4\GoodYear\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\GoodYear\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\GoodYear\system\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear...')
#15 {main}
CRITICAL - 2023-09-03 08:31:08 --> pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = \'mfajrihusaini05@gmail.com\'
              ^', 'C:\\ci4\\GoodYear\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 5 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "roles"
WHERE "email" = :email:
 LIMIT 1', [...], false)
 6 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 8 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 9 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
10 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
11 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
12 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
13 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 08:32:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 08:32:48 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^ in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\ci4\\GoodYear...', 187)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\ci4\GoodYear\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\ci4\GoodYear\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\GoodYear\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#8 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#9 C:\ci4\GoodYear\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#10 C:\ci4\GoodYear\system\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#11 C:\ci4\GoodYear\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#12 C:\ci4\GoodYear\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\GoodYear\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\GoodYear\system\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear...')
#15 {main}
CRITICAL - 2023-09-03 08:32:48 --> pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = \'mfajrihusaini05@gmail.com\'
              ^', 'C:\\ci4\\GoodYear\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 5 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "roles"
WHERE "email" = :email:
 LIMIT 1', [...], false)
 6 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 8 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 9 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
10 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
11 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
12 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
13 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 08:32:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:32:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:32:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:33:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 08:33:10 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^ in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\ci4\\GoodYear...', 187)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\ci4\GoodYear\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\ci4\GoodYear\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\GoodYear\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#8 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#9 C:\ci4\GoodYear\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#10 C:\ci4\GoodYear\system\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#11 C:\ci4\GoodYear\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#12 C:\ci4\GoodYear\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\GoodYear\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\GoodYear\system\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear...')
#15 {main}
CRITICAL - 2023-09-03 08:33:10 --> pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = \'mfajrihusaini05@gmail.com\'
              ^', 'C:\\ci4\\GoodYear\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 5 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "roles"
WHERE "email" = :email:
 LIMIT 1', [...], false)
 6 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 8 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 9 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
10 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
11 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
12 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
13 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 08:34:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 08:34:16 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^ in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\ci4\\GoodYear...', 187)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\ci4\GoodYear\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\ci4\GoodYear\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\GoodYear\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#8 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#9 C:\ci4\GoodYear\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#10 C:\ci4\GoodYear\system\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#11 C:\ci4\GoodYear\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#12 C:\ci4\GoodYear\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\GoodYear\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\GoodYear\system\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear...')
#15 {main}
CRITICAL - 2023-09-03 08:34:16 --> pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = \'mfajrihusaini05@gmail.com\'
              ^', 'C:\\ci4\\GoodYear\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 5 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "roles"
WHERE "email" = :email:
 LIMIT 1', [...], false)
 6 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 8 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 9 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
10 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
11 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
12 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
13 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 08:34:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:34:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 08:34:25 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^ in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\ci4\\GoodYear...', 187)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\ci4\GoodYear\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\ci4\GoodYear\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\GoodYear\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#8 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#9 C:\ci4\GoodYear\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#10 C:\ci4\GoodYear\system\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#11 C:\ci4\GoodYear\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#12 C:\ci4\GoodYear\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\GoodYear\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\GoodYear\system\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear...')
#15 {main}
CRITICAL - 2023-09-03 08:34:25 --> pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = \'mfajrihusaini05@gmail.com\'
              ^', 'C:\\ci4\\GoodYear\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 5 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "roles"
WHERE "email" = :email:
 LIMIT 1', [...], false)
 6 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 8 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 9 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
10 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
11 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
12 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
13 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
INFO - 2023-09-03 08:38:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:38:44 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:39:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:39:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-09-03 08:40:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-09-03 08:40:30 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^ in C:\ci4\GoodYear\system\Database\Postgre\Connection.php:187
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\ci4\\GoodYear...', 187)
#1 C:\ci4\GoodYear\system\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *\nFROM "...')
#2 C:\ci4\GoodYear\system\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\ci4\GoodYear\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\ci4\GoodYear\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\ci4\GoodYear\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\ci4\GoodYear\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#8 C:\ci4\GoodYear\vendor\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#9 C:\ci4\GoodYear\vendor\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#10 C:\ci4\GoodYear\system\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
#11 C:\ci4\GoodYear\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#12 C:\ci4\GoodYear\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\ci4\GoodYear\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\ci4\GoodYear\system\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear...')
#15 {main}
CRITICAL - 2023-09-03 08:40:30 --> pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = 'mfajrihusaini05@gmail.com'
              ^
in SYSTEMPATH\Database\Postgre\Connection.php on line 187.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Query failed: ERROR:  column &quot;email&quot; does not exist
LINE 3: WHERE &quot;email&quot; = \'mfajrihusaini05@gmail.com\'
              ^', 'C:\\ci4\\GoodYear\\system\\Database\\Postgre\\Connection.php', 187)
 2 SYSTEMPATH\Database\Postgre\Connection.php(187): pg_query(Object(PgSql\Connection), 'SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 3 SYSTEMPATH\Database\BaseConnection.php(692): CodeIgniter\Database\Postgre\Connection->execute('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 4 SYSTEMPATH\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM "roles"
WHERE "email" = \'mfajrihusaini05@gmail.com\'
 LIMIT 1')
 5 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM "roles"
WHERE "email" = :email:
 LIMIT 1', [...], false)
 6 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 7 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 8 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
 9 VENDORPATH\myth\auth\src\Authentication\LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate([...], true)
10 VENDORPATH\myth\auth\src\Controllers\AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt([...], false)
11 SYSTEMPATH\CodeIgniter.php(932): Myth\Auth\Controllers\AuthController->attemptLogin()
12 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
13 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
14 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
15 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\ci4\\GoodYear\\public\\index.php')
